from __future__ import annotations

from typing import TypeVar

from vibe.core.config._defaults import (
    DEFAULT_CONSOLE_BASE_URL,
    DEFAULT_MISTRAL_API_ENV_KEY,
    DEFAULT_MISTRAL_SERVER_URL,
    DEFAULT_THEME,
    DEFAULT_VIBE_BASE_URL,
)
from vibe.core.config._settings import (
    DEFAULT_MODELS,
    DEFAULT_PROVIDERS,
    DEFAULT_TRANSCRIBE_MODELS,
    DEFAULT_TRANSCRIBE_PROVIDERS,
    DEFAULT_TTS_MODELS,
    DEFAULT_TTS_PROVIDERS,
    TomlFileSettingsSource,
    VibeConfig,
    load_dotenv_values,
    resolve_api_key,
    resolve_theme_name,
)
from vibe.core.config.default_orchestrator import build_default_orchestrator
from vibe.core.config.layer import (
    ConfigLayer,
    ConfigLayerError,
    ConfigPatchApplicationError,
    EmptyLayerError,
    LayerImplementationError,
    LayerNotLoadedError,
    RawConfig,
    TrustNotResolvedError,
    TrustResolutionError,
    UntrustedLayerError,
)
from vibe.core.config.layers.agent_profile import AgentProfileLayer
from vibe.core.config.layers.default import DefaultConfigLayer
from vibe.core.config.layers.discovered import DiscoveredConfigLayer
from vibe.core.config.models import (
    THINKING_LEVELS,
    ConnectorConfig,
    ExperimentsConfig,
    MCPHttp,
    MCPOAuth,
    MCPServer,
    MCPStaticAuth,
    MCPStdio,
    MCPStreamableHttp,
    MissingAPIKeyError,
    ModelConfig,
    OtelSpanExporterConfig,
    ProjectContextConfig,
    ProviderConfig,
    SessionLoggingConfig,
    ThinkingLevel,
    TranscribeClient,
    TranscribeModelConfig,
    TranscribeProviderConfig,
    TTSClient,
    TTSModelConfig,
    TTSProviderConfig,
)
from vibe.core.config.patch import (
    AddOperationPatch,
    ConfigPatch,
    PatchOp,
    RemoveOperationPatch,
    ReplaceOperationPatch,
)
from vibe.core.config.schema import (
    ConfigDefinitionError,
    ConfigFragment,
    ConfigSchema,
    DuplicateMergeMetadataError,
    MergeFieldMetadata,
    WithConcatMerge,
    WithConflictMerge,
    WithDeepMerge,
    WithReplaceMerge,
    WithShallowMerge,
    WithUnionMerge,
)
from vibe.core.config.types import (
    MISSING_BACKING_STORE_DATA_FINGERPRINT,
    ConfigChangeCallback,
    ConfigChangeEvent,
    LayerConfigSnapshot,
)
from vibe.core.config.vibe_schema import VibeConfigSchema
from vibe.core.prompts import MissingPromptFileError

AnyVibeConfig = VibeConfig | VibeConfigSchema

VibeConfigT = TypeVar("VibeConfigT", bound=AnyVibeConfig)

__all__ = [
    "DEFAULT_CONSOLE_BASE_URL",
    "DEFAULT_MISTRAL_API_ENV_KEY",
    "DEFAULT_MISTRAL_SERVER_URL",
    "DEFAULT_MODELS",
    "DEFAULT_PROVIDERS",
    "DEFAULT_THEME",
    "DEFAULT_TRANSCRIBE_MODELS",
    "DEFAULT_TRANSCRIBE_PROVIDERS",
    "DEFAULT_TTS_MODELS",
    "DEFAULT_TTS_PROVIDERS",
    "DEFAULT_VIBE_BASE_URL",
    "MISSING_BACKING_STORE_DATA_FINGERPRINT",
    "THINKING_LEVELS",
    "AddOperationPatch",
    "AgentProfileLayer",
    "AnyVibeConfig",
    "ConfigChangeCallback",
    "ConfigChangeEvent",
    "ConfigDefinitionError",
    "ConfigFragment",
    "ConfigLayer",
    "ConfigLayerError",
    "ConfigPatch",
    "ConfigPatchApplicationError",
    "ConfigSchema",
    "ConnectorConfig",
    "DefaultConfigLayer",
    "DiscoveredConfigLayer",
    "DuplicateMergeMetadataError",
    "EmptyLayerError",
    "ExperimentsConfig",
    "LayerConfigSnapshot",
    "LayerImplementationError",
    "LayerNotLoadedError",
    "MCPHttp",
    "MCPOAuth",
    "MCPServer",
    "MCPStaticAuth",
    "MCPStdio",
    "MCPStreamableHttp",
    "MergeFieldMetadata",
    "MissingAPIKeyError",
    "MissingPromptFileError",
    "ModelConfig",
    "OtelSpanExporterConfig",
    "PatchOp",
    "ProjectContextConfig",
    "ProviderConfig",
    "RawConfig",
    "RemoveOperationPatch",
    "ReplaceOperationPatch",
    "SessionLoggingConfig",
    "TTSClient",
    "TTSModelConfig",
    "TTSProviderConfig",
    "ThinkingLevel",
    "TomlFileSettingsSource",
    "TranscribeClient",
    "TranscribeModelConfig",
    "TranscribeProviderConfig",
    "TrustNotResolvedError",
    "TrustResolutionError",
    "UntrustedLayerError",
    "VibeConfig",
    "VibeConfigSchema",
    "VibeConfigT",
    "WithConcatMerge",
    "WithConflictMerge",
    "WithDeepMerge",
    "WithReplaceMerge",
    "WithShallowMerge",
    "WithUnionMerge",
    "build_default_orchestrator",
    "load_dotenv_values",
    "resolve_api_key",
    "resolve_theme_name",
]
